specfile_path: packaging/fedora/snapd.spec
synced_files:
  - .packit.yaml
  - packaging/fedora/snapd.spec
upstream_project_name: snapd
downstream_package_name: snapd
create_tarball_command: ["packaging/pack-source", "-o", "packaging/fedora", "-g"]
current_version_command: ["git", "describe"]
